FROM python:3.8.16-bullseye
WORKDIR /usr/src/app
RUN apt update && apt install -y nginx
COPY dist/* /var/www/html
COPY nginx.conf /etc/nginx/sites-enabled/inky.conf
COPY /api .
RUN pip install -r requirements.txt
CMD python api.py