FROM node:latest as builder
WORKDIR /usr/src/app
COPY . .
RUN yarn
RUN yarn build

FROM python:3.8
WORKDIR /usr/src/app
RUN apt update && apt install -y nginx
COPY --from=builder /usr/src/app/dist/* /var/www/html
COPY nginx.conf /etc/nginx/sites-enabled/inky.conf
COPY /api .
RUN pip install -r requirements.txt
CMD python api.py